name: CI-CD

on: push

jobs:
  create-token-from-secret:
    name: Create tokens from secrets
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT | jq